development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:6bb2864476528d7ead7f8841bc7f49e5@porgy.redistogo.com:11306/
  # channel_prefix: share_square_production
